---
- name: ansible playbook to test ansible vault
  hosts: all
  become: true
  tasks:
  - name: clone a repo
    git:
      repo: git@github.com:abakade/vault.git
      dest: /opt/ansible_admin/test-vault
         
